module resm_l_shifter #(
    parameter lm = 23, le = 8
)(
    input [lm+3:0] in,
    input [le-1:0] shamt,
    output [lm+3:0] out  
);
    wire [$clog2(lm+3)-1:0] shamt_;
    genvar i;
    genvar j;

    assign shamt_ = shamt[$clog2(lm+3)-1:0]; // min is not required as left_shift shamt >= lm+3 can never be generated by the p_encoder
    generate
        for(i = 0;i <= lm+3;i = i + 1) begin: gen_loop
            wire [lm+3:0] mux_in; 
            for(j = 0;j <= lm+3; j = j + 1) begin: selector_in_loop
                if(j <= i)
                    assign mux_in[j] = in[i-j];
                else
                    assign mux_in[j] = 1'b0;
            end
            mux #(
                .W(1),
                .N(lm+4)
            ) out_i_mux
            (
                .in(mux_in),
                .sel(shamt_),
                .out(out[i])
            );
        end
    endgenerate
endmodule